### ISSUE TITLE
Port to other STM32- CPUs (as used in the various T12 controller modules)

### ISSUE THREAD

**Issue by kruebsam** [PTDreamer/stm32_soldering_iron_controller#1]
First of all: THANKS for your reengineering project and thanks for publishing your readings. I am sure all of us do appreciate that!

Of cause you do not have any personal advantage therein, but in order to increase the community of people using your code it would be of big advantage, if you would add the other CPU types been used so far (for those STM32 soldering controllers) to your code thus making it flexible enough to select which cpu to use for the destination controller.

Mine (dual controller for soldering iron and air gun) came with a STM32F101CBT
The newest (2018 New STM32 OLED T12 Digital Electric Soldering Irons Solder Station Controller Alloy DIY Kits V2.1S ) model comes with a STM32F102C8

**Comment by PTDreamer** [comment]
Hi,

Do you know if the other controllers you refer share the same hardware besides the processor. If not, all of the schematic would have to be reverse engineered. 
Even if it is just the processor it would be close to impossible to write the needed changes without real hardware to test with.
With that said if someone wants to donate a particular controller or contact the seller and see if he is willing to do it, I will certainly work on make it compatible.

**Comment by kruebsam** [comment]
I am pretty sure that the design in part will be different. For example: My dual-controller comes with two OLED-disdplays and two rotary encoders. Furthermore it does have functionality even to trigger valves and pumps. And it auto detects if a backup-battery is connected to the controller. If that is the case a further menu for setting date and time is available.
See https://www.aliexpress.com/item/Hot-Air-Gun-For-Soldering-Station-DIY-Electric-Power-Tools-STM32-Controller-Combo-Soldering-Iron-T12/32789490542.html for details on the dual-controller.

If there are a couple of others we could all throw a few bucks together and get Jose buying one of the controllers. Whom else to count in on that?

**Comment by PTDreamer** [comment]
Well that station uses the same processor for both the iron and the hot air gun, so it is not a port as the title of this issue states but a writing of all of the logic for a hot air gun, which honestly I'm not that interested, I have a different repository for a diy hot air gun, and that is what I use.

**Comment by kruebsam** [comment]
Thanks for your clear statement in this regard

**Comment by kruebsam** [comment]
Issue may be closed. Thanks!
