### ISSUE TITLE
Hardware issue - JBC stand contact

### ISSUE THREAD

**Issue by StefanTrethan** [PTDreamer/stm32_soldering_iron_controller#4]
Hi Jose, 

I have encountered another issue that makes absolutely no sense to me.
When trying the sleep stand contact there was a mighty flash (well, a tiny spark) and the transil diode D3 was gone along with the trace connecting it. The 2k2 did protect the STM so that's something.

Further investigation showed that the outer sleeve is pulsed to +24V as the power is on.

I triple checked, and triple checked again the connections per your diagram and they are correct.
If I reverse the middle and inner contact the outer sleeve will remain at ground potential, but the polarity of the thermocouple voltage is then reversed and I get no valid temperature reading.
(The center pin makes a positive voltage against the middle contact when the tip is heated).

I have seen a ground-open picture of the JBC tips, and the center rod is welded to the outer sleeve directly. The middle contact goes to the end of the heater coil. Therefore I am not surprised my outer sleeve gets pulsed to +24 if the center rod is connected to the Mosfet, but I see no way how this could work? Either the thermocouple voltage has the wrong polarity, or I get +24V at the outside as the Mosfet is on.

Please advise if there is anything I am missing here.
You wrote in your blog that you connect the outer sleeve to GND via a switch, but I just don't see how this is possible without shorting out the heater?
Please check on your tips if there is a connection between the center pin and outer sleeve.

Thank you.

ST

**Comment by StefanTrethan** [comment]
I separated the thermocouple voltage measurement input (R8 C7 in your schematic) from the mosfet and made the following connections to the iron:

inner contact: to the measurement input (R8 C7)
middle contact: to the Mosfet Q1
Outer sleeve: to GND.

This is the only way to keep the outer sleeve at ground potential at all times and still measure positive thermocouple voltages. I don't think this is how JBC does it, but they have two mosfets and/or may be able to measure negative thermocouple voltages, neither of which I was prepared to do.

I have no idea how this could ever work for you with the connections made as indicated on your blog. I consider it physically impossible and I think there must be a mistake somewhere.
I hope you get the chance to review this.

Now the stand contact works.

ST

**Comment by PTDreamer** [comment]
What tips are you using? I just checked again and also made a video with T-210 tips everything is as it should.
Outer contact is chassis, middle is ground (about 1ohm between the two), inner contact is V+ (about 3ohm to gnd).

Video is still uploading, will post link later.

**Comment by StefanTrethan** [comment]
I am using T245 tips. I checked a bunch of them and all have the outer
contact welded to the center contact.
You can see a sketch of the internal workings here:

https://photos.app.goo.gl/tIwbQ8vBmHJgyNNA2

As you can see the outer contact is connected to the other two (with some
heater resistance to the middle one).

Do you have no connection to the outer contact?

ST

**Comment by StefanTrethan** [comment]
You can see the cross section picture here:
http://dangerousprototypes.com/forum/download/file.php?id=11012&mode=view

Perhaps the T-210 might be different?

ST

**Comment by PTDreamer** [comment]
There's something which doesn't make sense. According to the instructions on the blog in order to use the stand for the sleep function you should connect the chassis ground to ground. That means that both the outer and middle tip contact should be at ground potential, so how can you have any voltage on the tip outer shell?

**Comment by StefanTrethan** [comment]
When I connect chassis ground to ground as per the blog it shorts the power
supply out as soon as the fet turns on.
The outer and middle contact are not always at the same potential, since
the heater element is between the two, look at the cut away photo.

The center pin/rod is a different metal, forming a thermocouple with the
two stainless tubes.
You can measure positive voltage (mV) between the center pin and the middle
contact, and the same voltage between the center pin and outer shell if you
heat the tip up.
There is no voltage measured between the outer shell and middle contact
with the tip disconnected from power, since only the heater is between the
two and the tubes are of the same metal.

The middle contact has the spiral heating element welded to it, and the
other end of the heating element joins the same point as the thermocouple.

The instructions on the blog must be mistaken, or I misunderstand them, or
the 210 is different from the 245.

I'm confident the stand contact can never work as instructed on the blog,
at the same time I know you understand very well what you do and clearly it
does work for you, so I really have no explanation for this.

ST

**Comment by PTDreamer** [comment]
Hi,

This is the first time I read this on a proper screen, been using the phone all day even for the video.
Yes it seems there is little doubt that the 210's are constructed differently.
If I read the design correctly you can even sample the TC voltage at the same time you pulse ground, ie, 24V constant at outer shell, and pulsed ground to middle jacket. Inner pin should have TC voltage independent of pulse duty cycle.
This is not possible with 210's where you have to stop pulsing, wait, sample TC, continue.

If you don't mind I will post your findings on the blog together with your workaround.

**Comment by StefanTrethan** [comment]
I don't think you can sample TC with the power on, the voltage drop in the
ground lead would mess things up.

Too bad I don't have any 210 to check for myself (sometimes you need to see
with your own eyes), but I do have the tweezers at work which use small
tips and will compare them monday.

Of course you can use anything you want on the blog.

I'm just glad it works now. I wanted to build a battery powered station for
some time now and when I saw your blog I was happy to find a ready-made
solution.
Of course I did not expect to run into this difficulty, but a little bit of
work has hurt nobody.

ST

**Comment by PTDreamer** [comment]
> Too bad I don't have any 210 to check for myself (sometimes you need to see
with your own eyes), but I do have the tweezers at work which use small
tips and will compare them monday.

Let me know if you want me to test something so you can have some piece of mind :)
I have updated the blog, will wait to hear from you monday and will leave the issue open till then.
I did find a picture which shows different connections for the two types of tip, but decided not to post it because according to my tests the connections shown for the 210s are wrong.

**Comment by StefanTrethan** [comment]
I just checked the C120 tips and you are right. I mean we are both right,
they are different.

Maybe they can not construct the smaller tips the same way as the larger
ones?
This means we can not just plug any iron into the chinese controller, but
that is OK with me, I don't have a 210 handle.

Thanks again for providing the software.
I had hoped this would be ready-made work, but as always it didn't go
without putting a few hours in (and the mechanics are still to come).
But now it is working fine and that is what counts.

ST

**Comment by PTDreamer** [comment]
At least now we know. Thanks!
