### ISSUE TITLE
low value of calADC_At_200 causes power output to be stuck at 100%

### ISSUE THREAD

**Issue by JMoerman** [PTDreamer/stm32_soldering_iron_controller#5]
(I have yet to upgrade to 1.1.2, but taking a quick look at the commits, nothing seems to have been changed since 1.0)

I recently got a new 1403 t12 tip and calibrated this tip with the tip thermometer resulting in the calibration values 175, 1075 and 2147. This resulted in accurate temperature measurements, but also caused the output power to be stuck at 100%, quickly heating my iron to above 500C (which it displays correctly).
I managed to find the debug menu and found out that a higher value for calADC_At_200 alleviated the issue.

(When I had increased calADC_At_200 a bit the soldering iron operated normally unless the temperature was set to a value lower than 140C. I did not investigate much longer as my tip already has a purplish to blueish color from the brief exposure to the high power output.)

**Comment by ricktendo** [comment]
I had the EXACT same issue, I reported it in the [EEVBlog forum](http://www.eevblog.com/forum/reviews/stm32-oled-digital-soldering-station-for-t12-handle/msg1893620/#msg1893620).

Another thing that does not always work is sleep, is there any way to adjust the sensitivity?

**Comment by JMoerman** [comment]
@ricktendo No idea, I'm just another user.
I'm going to build a stand that is able to detect the iron first, after that I will take a look at if I can get sleeping to work well. (The switch in my handle is never going to work well for this.)

Since you also have this issue, do you know how to get into the debug menu? (configure pid -> push and hold button and twist untill you reach a screen with 5 values and no name. The 3rd value is calADC_At_200)

**Comment by PTDreamer** [comment]
Issue should be fixed now. Please test and report.

**Comment by ricktendo** [comment]
Thank you PTDreamer, I flashed the latest firmware, I configured sleep for 15s but the iron would not go into sleep mode so I cannot verify if the issue is fixed. Maybe JMoerman has better luck.

**Comment by JMoerman** [comment]
Got around to updating the iron and it no longer heated the iron beyond what was set. I will need to do some more thorough testing, but I consider this fixed.

@ricktendo sleeping issues are a bit out of the scope of this issue. You may want to open a separate issue for that.
