### ISSUE TITLE
A small ask - can enable 'git lfs' feature? Thank you

### ISSUE THREAD

**Issue by dreamcat4** [PTDreamer/stm32_soldering_iron_controller#7]
Hi PTDreamer!

For this project (STM32 Controller)... I wish to store git LFS object reference in my fork. For archiving supporting materials. To keep them safe and available when people do `git clone`. The reason is to avoid needing to store assets with a larger file size right next to the source code itself. Instead just only a reference is saved. So that adding further assets does not blow up the size of the git repo. Which is not desirable for others checking out / downloading. etc.

*For example:*

One of the resources I wish to backup (using the git LFS feature) are your blog posts all about this STM32 project. Just in case your personal wordpress blog breaks / fails one day. This then makes sure the project continues. And without missing docs which is referenced etc.

**My problem:**

Github does not let **me** enable the `git lfs` feature on my fork. Unless the original repo (yours) is first enable with git LFS feature: 

https://github.com/git-lfs/git-lfs/issues/1449#issuecomment-477601707

If you can enable this feature. Then it would be a great help, & thank you. Because [otherwise] I do not actually wish to unlink my repo from yours. It's nice to keep them connected on github. So that people can see in the network graph, check the activity across the forks. And find the other active branches, do merges / etc.

Sorry to have to ask you to step in here, it is silly, and should not be required. However if you can enable LFS in your repo. I believe this is the known workaround:

https://github.com/git-lfs/git-lfs/issues/1449#issuecomment-239831273

So pushing a dummy file, added as an LFS object reference. Then I can fork the repo again but this time with LFS object inside it.... Then you can remove that dummy Git LFS reference in a subsequent commit.

That would save me a whole heap of problem. Because it's better (for sharing the code) to keep my repo status as a fork of your original repo. It is better for the open source visibility. Thanks for considering this.

**Comment by dreamcat4** [comment]
Here is a guide, to show how to do this thing, to enable LFS:

https://git-lfs.github.com/

**Comment by PTDreamer** [comment]
Hi, should be working, please test

**Comment by dreamcat4** [comment]
Hey @PTDreamer it worked! Thank you so much.

https://github.com/dreamcat4/stm32_soldering_iron_controller/commit/694e6fc8c9641aa407df7312de831f2c6c7b0dd9

**Comment by dreamcat4** [comment]
Ok I have saved these LFS commit into a seperate branch, taken it off my master branch.

Perhaps if you also want to force roll back -1 commit. To save from the extra 13mb. Then you can go ahead. It should still remain here in my fork's commit history. In that other branch I made for it.

Thanks again! Good day.
